version: '3.9'

services:

  frontend:
    container_name: frontend
    image: yur0n/tubescope-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    container_name: backend
    image: yur0n/tubescope-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8880:8880
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=8880
    # depends_on:
    #   - mongo

# CHANGE TO SUPABASE local
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   restart: always
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=pickels
  #     - MONGO_INITDB_ROOT_PASSWORD=D4zfQQt5Zj7FSWu8
  #   volumes:
  #     - pgdata:/var/lib/mongo/data

volumes:
  pgdata: {}