
name: main

on: 
  push:
    branches:
      - "main"
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add API_KEY from Secrets
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" >> .env
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Images
        run: docker compose build
        shell: bash
      - uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "compose.yml"
      - name: Wait 30 seconds
        run: |
          sleep 30
        shell: bash
      - name: Push backend
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tubescope-backend:latest
      - name: Push frontend
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tubescope-frontend:latest
