
name: ci

on: 
  push:
    branches:
      - "main"
  repository_dispatch:
    types: [do-workflow]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./compose.yml"

# jobs:
#   build-and-run:
#     runs-on: ubuntu-latest
#     steps:
#       - 
#         uses: actions/checkout@v4
#       - 
#         uses: isbang/compose-action@v1.5.1
#         with:
#           compose-file: "./compose.yml"
#       - 
#         name: Add SSH key to ssh-agent
#         run: |
#           echo "${{ secrets.DEPLOY_KEY }}" > deploy_key
#           chmod 600 deploy_key
#           eval "$(ssh-agent -s)"
#           ssh-add deploy_key
#       - 
#         name: Deploy to server
#         if: ${{ success() }}
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "docker-compose -f /path/to/docker-compose.yml down"
#           scp docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/path/to/docker-compose.yml
#           ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "docker-compose -f /path/to/docker-compose.yml up -d"
